name: green_pnp_real

image_shape: [3, 84, 84]
dataset_path: ../data/green_pnp/


shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    ee_rgb_camera:
      shape: [3, 84, 84]
      type: rgb
    front_rgb_camera:
      shape: [3, 84, 84]
      type: rgb
    robot_state:
      shape: [16]
      type: low_dim
  action: 
    shape : [7]
    # franka_gripper : [1]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_image_dataset.RealImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False